#testando os tipos de variaveis
a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('É um nunero? ', a.isnumeric())
print('Só tem espaço? ', a.isspace())
print('Só tem letras? ', a.isalpha())
print('É alfanumerico? ', a.isalnum())
print('Está em maiúsculas? ', a.isupper())
print('Está em minúsculas? ', a.islower())
print('Está capitalizada? ', a.istitle())
